"""
Citation Service for ResearchLens.
Formats citations from ChromaDB metadata — citations are NEVER generated by the LLM.
This is the core principle: every citation traces back to stored vector metadata.
"""
from typing import List, Dict, Any, Optional
from app.models.schemas import CitationModel


def format_citations_from_results(results: Dict[str, Any]) -> List[CitationModel]:
    """
    Extract citation models from ChromaDB query results.
    
    ChromaDB returns results in this structure:
    {
        'ids': [['id1', 'id2', ...]],
        'documents': [['text1', 'text2', ...]],
        'metadatas': [[{...}, {...}, ...]],
        'distances': [[0.5, 0.7, ...]]
    }
    
    Citations are built entirely from stored metadata — never from LLM output.
    """
    citations = []
    
    if not results:
        return citations
    
    metadatas = results.get('metadatas')
    documents = results.get('documents')
    distances = results.get('distances')
    
    if not metadatas or not metadatas[0]:
        return citations
    
    metas = metadatas[0]
    docs = documents[0] if documents else [None] * len(metas)
    dists = distances[0] if distances else [None] * len(metas)
    
    for i in range(len(metas)):
        meta = metas[i]
        
        citation = CitationModel(
            document_name=meta.get('document_name', 'Unknown Document'),
            page_number=meta.get('page_number', 0),
            section=meta.get('section', None),
            chunk_index=meta.get('chunk_index', i),
            evidence_text=docs[i] if docs[i] else '',
            relevance_score=round(dists[i], 4) if dists[i] is not None else None,
        )
        citations.append(citation)
    
    # Deduplicate — same document + same chunk_index = same evidence
    seen = set()
    unique_citations = []
    for c in citations:
        key = f"{c.document_name}::{c.chunk_index}"
        if key not in seen:
            seen.add(key)
            unique_citations.append(c)
    
    # Sort by relevance (lower distance = more relevant)
    unique_citations.sort(key=lambda c: c.relevance_score if c.relevance_score is not None else float('inf'))
    
    return unique_citations


def group_citations_by_document(citations: List[CitationModel]) -> Dict[str, List[CitationModel]]:
    """
    Group citations by document name.
    Used for multi-paper comparison to keep sources segregated.
    """
    grouped: Dict[str, List[CitationModel]] = {}
    for citation in citations:
        doc_name = citation.document_name
        if doc_name not in grouped:
            grouped[doc_name] = []
        grouped[doc_name].append(citation)
    return grouped
